language: elixir

elixir:
  - 1.10.0
otp_release:
  - 22.2

services:
  - mysql

env:
  global:
    - "ENV=test"
    - "MIX_ENV=test"
    - "TEST_DATABASE_USERNAME=travis"
    - "TEST_DATABASE_PASSWORD="

script:
  - mix do clean, compile --warnings-as-errors, test --exclude skip_on_ci
